### ISSUE TITLE
Use black to automate style

### ISSUE THREAD

**Issue by k-collie** [kj5248/python-intermediate-inflammation#3]
Can use in `.pre-commit-config.yaml` as follows:

```
# Use `pre-commit autoupdate` to auto-bump all revisions

repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
    - id: check-toml
    - id: check-yaml
    - id: end-of-file-fixer
    - id: mixed-line-ending
    - id: no-commit-to-branch
      args: [--branch, main, --branch, testing]
    - id: trailing-whitespace

-   repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
    - id: black
```

```bash
pip install pre-commit
pre-commit install
```

code will be formatted and linted before git commit.
